CREATE TABLE STAFFUSER.DB_MAJOR (
MAJOR_NO CHAR(4), 
MAJOR_NAME VARCHAR2(20), 
COLLEGE_NO CHAR(2), 
CONSTRAINT FK_COLLEGE_NO FOREIGN KEY (COLLEGE_NO) REFERENCES STAFFUSER.DB_COLLEGE (COLLEGE_NO) VALIDATE, 
CONSTRAINT PK_MAJOR_NO PRIMARY KEY (MAJOR_NO) VALIDATE ) 
TABLESPACE TBS_MAIN 
PCTFREE 10 
INITRANS 1 
MAXTRANS 255 
STORAGE ( BUFFER_POOL DEFAULT) 
LOGGING NOCOMPRESS
/
