CREATE TABLE DB_FACULTY_PER(
WORK_ID         CHAR(6) NOT NULL, 
LOGIN_PWD_F     VARCHAR2(20), 
PWD_TIP1_F      VARCHAR2(20), 
PWD_ANSWER1_F   VARCHAR2(16), 
PASSOWOD_TIP2_F VARCHAR2(20),
PWD_ANSWER2_F   VARCHAR2(16),
CONSTRAINT PK_FACULTY_PER_WID PRIMARY KEY (WORK_ID) VALIDATE ) 
TABLESPACE TBS_TEACH_STD 
PARALLEL
/