CREATE TABLE DB_STUDENT_PER(
REGISTER_NO CHAR(12),
LOGIN_PWD_S VARCHAR2(20),
PWD_TIP1_S VARCHAR2(20), 
PWD_ANSWER1_S VARCHAR2(16), 
PASSOWOD_TIP2_S VARCHAR2(20),
PWD_ANSWER2_S VARCHAR2(16), 
CONSTRAINT PK_STUDENT_PER_REGIST_NO PRIMARY KEY (REGISTER_NO) VALIDATE )
TABLESPACE TBS_TEACH_STD
PCTFREE 10 
INITRANS 1
MAXTRANS 255 
STORAGE ( BUFFER_POOL DEFAULT)
 LOGGING NOCOMPRESS 
PARALLEL
/