CREATE TABLE db_major_teacher(
WORK_ID            CHAR(6)     NOT NULL, 
REGISTER_NO        CHAR(12)    NOT NULL,
CONSTRAINT PK_RNO_WID PRIMARY KEY(REGISTER_NO,WORK_ID) VALIDATE,
CONSTRAINT FK_MT_REGISTER_NO FOREIGN KEY(REGISTER_NO) REFERENCES DB_STUDENT(REGISTER_NO) VALIDATE,
CONSTRAINT FK_MT_WID FOREIGN KEY(WORK_ID) REFERENCES DB_TEACHER(WORK_ID) VALIDATE)
ORGANIZATION INDEX TABLESPACE TBS_MAIN 
PCTFREE 10 
INITRANS 50 
MAXTRANS 4 
STORAGE (BUFFER_POOL KEEP) 
LOGGING NOCOMPRESS
PARALLEL
/

