CREATE USER staffuser PROFILE DEFAULT IDENTIFIED BY "staffuser123" 
DEFAULT TABLESPACE  tbs_main 
TEMPORARY TABLESPACE tbs_temp 
QUOTA UNLIMITED ON tbs_art_fash_busi 
QUOTA UNLIMITED ON tbs_bio_foo 
QUOTA UNLIMITED ON tbs_index 
QUOTA UNLIMITED ON tbs_infor_mati 
QUOTA UNLIMITED ON tbs_main 
QUOTA UNLIMITED ON tbs_teach_std 
ACCOUNT UNLOCK
/
GRANT CREATE INDEXTYPE TO staffuser
/
GRANT CREATE VIEW TO staffuser
/
GRANT CONNECT TO staffuser
/
GRANT RESOURCE TO staffuser
/
