CREATE USER dbsysuser  PROFILE DEFAULT IDENTIFIED BY "dbsysuser123" 
DEFAULT TABLESPACE tbs_main 
TEMPORARY TABLESPACE tbs_temp 
ACCOUNT UNLOCK
/
GRANT SYSDBA TO dbsysuser
/
GRANT CONNECT TO dbsysuser
/
GRANT DBA TO dbsysuser
/
GRANT RESOURCE TO dbsysuser
/
