GRANT DELETE ON STAFFUSER.DB_GRADE TO STDUSER
/
GRANT INSERT ON STAFFUSER.DB_GRADE TO STDUSER
/
GRANT SELECT ON STAFFUSER.DB_GRADE TO STDUSER
/
GRANT SELECT ON STAFFUSER.DB_STUDENT TO STDUSER
/
GRANT UPDATE ON STAFFUSER.DB_STUDENT TO STDUSER
/
GRANT SELECT ON STAFFUSER.DB_TEACHER TO STDUSER
/