CREATE SMALLFILE TABLESPACE Tbs_main 
DATAFILE
'C:\app\james_000\oradata\EnterDB\Tbs_main1.ora' SIZE 250M 
AUTOEXTEND ON 
NEXT 25M 
MAXSIZE UNLIMITED,
'C:\app\james_000\oradata\EnterDB\Tbs_main2.ora' SIZE 250M 
AUTOEXTEND ON 
NEXT 25K 
MAXSIZE UNLIMITED 
LOGGING 
EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT AUTO
/