CREATE SMALLFILE TABLESPACE Tbs_bio_foo DATAFILE
'C:\app\james_000\oradata\EnterDB\Tbs_bio_foo1.ora' SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE UNLIMITED,
'C:\app\james_000\oradata\EnterDB\Tbs_bio_foo2.ora' SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE UNLIMITED 
LOGGING 
EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT AUTO