CREATE SMALLFILE TABLESPACE Tbs_infor_mati DATAFILE
'C:\app\james_000\oradata\EnterDB\Tbs_infor_mati1.ora' SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE UNLIMITED,
'C:\app\james_000\oradata\EnterDB\Tbs_infor_mati2.ora' SIZE 100M 
AUTOEXTEND ON 
NEXT 10M
MAXSIZE UNLIMITED 
LOGGING 
EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT AUTO
/



