CREATE SMALLFILE TABLESPACE Tbs_teach_std 
DATAFILE
'C:\app\james_000\oradata\EnterDB\Tbs_teach_std1.ora' SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE UNLIMITED,
'C:\app\james_000\oradata\EnterDB\Tbs_teach_std2.ora' SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE UNLIMITED 
LOGGING 
EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT AUTO