CREATE SMALLFILE TABLESPACE Tbs_index 
DATAFILE 'C:\app\james_000\oradata\EnterDB\tbs_index1.ora' SIZE 100M , 
'C:\app\james_000\oradata\EnterDB\tbs_index2.ora' SIZE 100M 
LOGGING
EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT AUTO
/

ALTER DATABASE 
DATAFILE 'C:\app\james_000\oradata\EnterDB\TBS_INDEX2.ORA' 
AUTOEXTEND ON NEXT 10M
/
ALTER DATABASE 
DATAFILE 'C:\app\james_000\oradata\EnterDB\TBS_INDEX1.ORA' 
AUTOEXTEND ON NEXT 10M
/