CREATE SMALLFILE TEMPORARY TABLESPACE "TBS_TEMP" 
TEMPFILE 
'C:\app\james_000\oradata\EnterDB\tbs_temp1' SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE UNLIMITED ,
 'C:\app\james_000\oradata\EnterDB\tbs_temp2' SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE UNLIMITED 
EXTENT MANAGEMENT LOCAL 
UNIFORM SIZE 1M
/